### ISSUE TITLE
Does not work on Microsoft Edge

### ISSUE THREAD

**Issue by ocdtrekkie** [ghuser-io/ghuser.io#180]
I have a Windows Mobile phone with Microsoft Edge, and the spinner for my profile just cycles endlessly. I also tested with desktop Edge, and it does the same thing.

**Comment by venarius** [comment]
Managed to reproduce it and got the following error in the Edge Console:
`SCRIPT1028: Expected identifier, string or number`

Turns out, that issue is bigger than initially thought. MS Edge doesn't support property rest yet...
https://stackoverflow.com/questions/53628191/edge-script1028-expected-identifier-string-or-number

Two ways to resolve this issue:
* Rewrite every function that uses property rest. This is going to be a whole lot...
* Compile the whole project into ES5 using babel

I think it's not worth the effort and it would be best to just wait until Edge supports property resting.

**Comment by ocdtrekkie** [comment]
Well, I mean, now that Microsoft has abandoned Edge and committed to just reskinning Chrome... yeah, not much point worrying about Edge compat.

**Comment by AurelienLourot** [comment]
Closing then, thanks!
